name: OS X

on:
  push:
    branches: [ master ]
    tags: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  osx_wheel:
    runs-on: macos-10.15

    steps:
      - name: checkout
        uses: actions/checkout@v2

      # first test it without any gobject packages installed
      - name: Run test Suite
        run:  make test

      - name: Install homebrew packages
        run: make osx

      - name: Install GUI python requirements
        run: venv/bin/pip install -e "."

      # run test suite again with GUI deps installed
      - name: Run test Suite
        run:  make test